version: "2"
volumes:
  node_modules:
services:
  app:
    environment:
      - NODE_ENV=development
      - NODE_PORT=33333
    ports:
      - '3333:3333'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
      - /src/node_modules
